apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: p2p-lending

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
      - name: api-gateway
        image: shriaarch/api-gateway:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:
        - name: PORT
          value: "3000"

        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"

        - name: LOAN_SERVICE_URL
          value: "http://loan-service:3002"