apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  namespace: p2p-lending

spec:
  replicas: 1

  selector:
    matchLabels:
      app: loan-service

  template:
    metadata:
      labels:
        app: loan-service

    spec:
      containers:
      - name: loan-service
        image: shriaarch/loan-service:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 3002

        env:
        - name: PORT
          value: "3002"

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: p2p-config
              key: DB_HOST

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: p2p-config
              key: DB_PORT

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: p2p-config
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: p2p-config
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: p2p-secret
              key: DB_PASSWORD

        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: p2p-config
              key: JWT_SECRET